// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FirefamErrorInfo } from "./FirefamErrorInfo";

export type TurnError = { message: string, firefamErrorInfo: FirefamErrorInfo | null, additionalDetails: string | null, };
