use crate::bespoke_event_handling::apply_bespoke_event_handling;
use crate::bespoke_event_handling::maybe_emit_hook_prompt_item_completed;
use crate::command_exec::CommandExecManager;
use crate::command_exec::StartCommandExecParams;
use crate::config_manager::ConfigManager;
use crate::error_code::INPUT_TOO_LARGE_ERROR_CODE;
use crate::error_code::invalid_params;
use crate::models::supported_models;
use crate::outgoing_message::ConnectionId;
use crate::outgoing_message::ConnectionRequestId;
use crate::outgoing_message::OutgoingMessageSender;
use crate::outgoing_message::RequestContext;
use crate::outgoing_message::ThreadScopedOutgoingMessageSender;
use crate::skills_watcher::SkillsWatcher;
use crate::thread_status::ThreadWatchManager;
use crate::thread_status::resolve_thread_status;
use chrono::Duration as ChronoDuration;
use chrono::SecondsFormat;
use firefam_analytics::AnalyticsEventsClient;
use firefam_analytics::AnalyticsJsonRpcError;
use firefam_analytics::InputError;
use firefam_analytics::TurnSteerRequestError;
use firefam_app_server_protocol::Account;
use firefam_app_server_protocol::AccountLoginCompletedNotification;
use firefam_app_server_protocol::AccountUpdatedNotification;
use firefam_app_server_protocol::AddCreditsNudgeCreditType;
use firefam_app_server_protocol::AddCreditsNudgeEmailStatus;
use firefam_app_server_protocol::AppInfo;
use firefam_app_server_protocol::AppListUpdatedNotification;
use firefam_app_server_protocol::AppSummary;
use firefam_app_server_protocol::AppsListParams;
use firefam_app_server_protocol::AppsListResponse;
use firefam_app_server_protocol::AskForApproval;
use firefam_app_server_protocol::AuthMode;
use firefam_app_server_protocol::CancelLoginAccountParams;
use firefam_app_server_protocol::CancelLoginAccountResponse;
use firefam_app_server_protocol::CancelLoginAccountStatus;
use firefam_app_server_protocol::ClientInfo;
use firefam_app_server_protocol::ClientRequest;
use firefam_app_server_protocol::ClientResponsePayload;
use firefam_app_server_protocol::CollaborationModeListParams;
use firefam_app_server_protocol::CollaborationModeListResponse;
use firefam_app_server_protocol::CommandExecParams;
use firefam_app_server_protocol::CommandExecResizeParams;
use firefam_app_server_protocol::CommandExecTerminateParams;
use firefam_app_server_protocol::CommandExecWriteParams;
use firefam_app_server_protocol::ConfigWarningNotification;
use firefam_app_server_protocol::ConversationGitInfo;
use firefam_app_server_protocol::ConversationSummary;
use firefam_app_server_protocol::DeprecationNoticeNotification;
use firefam_app_server_protocol::DynamicToolSpec as ApiDynamicToolSpec;
use firefam_app_server_protocol::EnvironmentAddParams;
use firefam_app_server_protocol::EnvironmentAddResponse;
use firefam_app_server_protocol::ExperimentalFeature as ApiExperimentalFeature;
use firefam_app_server_protocol::ExperimentalFeatureListParams;
use firefam_app_server_protocol::ExperimentalFeatureListResponse;
use firefam_app_server_protocol::ExperimentalFeatureStage as ApiExperimentalFeatureStage;
use firefam_app_server_protocol::FeedbackUploadParams;
use firefam_app_server_protocol::FeedbackUploadResponse;
use firefam_app_server_protocol::FirefamErrorInfo;
use firefam_app_server_protocol::GetAccountParams;
use firefam_app_server_protocol::GetAccountRateLimitsResponse;
use firefam_app_server_protocol::GetAccountResponse;
use firefam_app_server_protocol::GetAuthStatusParams;
use firefam_app_server_protocol::GetAuthStatusResponse;
use firefam_app_server_protocol::GetConversationSummaryParams;
use firefam_app_server_protocol::GetConversationSummaryResponse;
use firefam_app_server_protocol::GitDiffToRemoteParams;
use firefam_app_server_protocol::GitDiffToRemoteResponse;
use firefam_app_server_protocol::GitInfo as ApiGitInfo;
use firefam_app_server_protocol::HookMetadata;
use firefam_app_server_protocol::HooksListParams;
use firefam_app_server_protocol::HooksListResponse;
use firefam_app_server_protocol::InitializeParams;
use firefam_app_server_protocol::InitializeResponse;
use firefam_app_server_protocol::JSONRPCErrorError;
use firefam_app_server_protocol::ListMcpServerStatusParams;
use firefam_app_server_protocol::ListMcpServerStatusResponse;
use firefam_app_server_protocol::LoginAccountParams;
use firefam_app_server_protocol::LoginAccountResponse;
use firefam_app_server_protocol::LoginApiKeyParams;
use firefam_app_server_protocol::LogoutAccountResponse;
use firefam_app_server_protocol::MarketplaceAddParams;
use firefam_app_server_protocol::MarketplaceAddResponse;
use firefam_app_server_protocol::MarketplaceInterface;
use firefam_app_server_protocol::MarketplaceRemoveParams;
use firefam_app_server_protocol::MarketplaceRemoveResponse;
use firefam_app_server_protocol::MarketplaceUpgradeErrorInfo;
use firefam_app_server_protocol::MarketplaceUpgradeParams;
use firefam_app_server_protocol::MarketplaceUpgradeResponse;
use firefam_app_server_protocol::McpResourceReadParams;
use firefam_app_server_protocol::McpResourceReadResponse;
use firefam_app_server_protocol::McpServerOauthLoginCompletedNotification;
use firefam_app_server_protocol::McpServerOauthLoginParams;
use firefam_app_server_protocol::McpServerOauthLoginResponse;
use firefam_app_server_protocol::McpServerRefreshResponse;
use firefam_app_server_protocol::McpServerStatus;
use firefam_app_server_protocol::McpServerStatusDetail;
use firefam_app_server_protocol::McpServerToolCallParams;
use firefam_app_server_protocol::McpServerToolCallResponse;
use firefam_app_server_protocol::MemoryResetResponse;
use firefam_app_server_protocol::MockExperimentalMethodParams;
use firefam_app_server_protocol::MockExperimentalMethodResponse;
use firefam_app_server_protocol::ModelListParams;
use firefam_app_server_protocol::ModelListResponse;
use firefam_app_server_protocol::PermissionProfileListParams;
use firefam_app_server_protocol::PermissionProfileListResponse;
use firefam_app_server_protocol::PermissionProfileSummary;
use firefam_app_server_protocol::PluginDetail;
use firefam_app_server_protocol::PluginInstallParams;
use firefam_app_server_protocol::PluginInstallResponse;
use firefam_app_server_protocol::PluginInstalledParams;
use firefam_app_server_protocol::PluginInstalledResponse;
use firefam_app_server_protocol::PluginInterface;
use firefam_app_server_protocol::PluginListMarketplaceKind;
use firefam_app_server_protocol::PluginListParams;
use firefam_app_server_protocol::PluginListResponse;
use firefam_app_server_protocol::PluginMarketplaceEntry;
use firefam_app_server_protocol::PluginReadParams;
use firefam_app_server_protocol::PluginReadResponse;
use firefam_app_server_protocol::PluginShareCheckoutParams;
use firefam_app_server_protocol::PluginShareCheckoutResponse;
use firefam_app_server_protocol::PluginShareContext;
use firefam_app_server_protocol::PluginShareDeleteParams;
use firefam_app_server_protocol::PluginShareDeleteResponse;
use firefam_app_server_protocol::PluginShareDiscoverability;
use firefam_app_server_protocol::PluginShareListItem;
use firefam_app_server_protocol::PluginShareListParams;
use firefam_app_server_protocol::PluginShareListResponse;
use firefam_app_server_protocol::PluginSharePrincipal;
use firefam_app_server_protocol::PluginSharePrincipalType;
use firefam_app_server_protocol::PluginShareSaveParams;
use firefam_app_server_protocol::PluginShareSaveResponse;
use firefam_app_server_protocol::PluginShareTarget;
use firefam_app_server_protocol::PluginShareUpdateDiscoverability;
use firefam_app_server_protocol::PluginShareUpdateTargetsParams;
use firefam_app_server_protocol::PluginShareUpdateTargetsResponse;
use firefam_app_server_protocol::PluginSkillReadParams;
use firefam_app_server_protocol::PluginSkillReadResponse;
use firefam_app_server_protocol::PluginSource;
use firefam_app_server_protocol::PluginSummary;
use firefam_app_server_protocol::PluginUninstallParams;
use firefam_app_server_protocol::PluginUninstallResponse;
use firefam_app_server_protocol::RequestId;
use firefam_app_server_protocol::ReviewDelivery as ApiReviewDelivery;
use firefam_app_server_protocol::ReviewStartParams;
use firefam_app_server_protocol::ReviewStartResponse;
use firefam_app_server_protocol::ReviewTarget as ApiReviewTarget;
use firefam_app_server_protocol::SandboxMode;
use firefam_app_server_protocol::SendAddCreditsNudgeEmailParams;
use firefam_app_server_protocol::SendAddCreditsNudgeEmailResponse;
use firefam_app_server_protocol::ServerNotification;
use firefam_app_server_protocol::ServerRequestResolvedNotification;
use firefam_app_server_protocol::SkillSummary;
use firefam_app_server_protocol::SkillsConfigWriteParams;
use firefam_app_server_protocol::SkillsConfigWriteResponse;
use firefam_app_server_protocol::SkillsListParams;
use firefam_app_server_protocol::SkillsListResponse;
use firefam_app_server_protocol::SortDirection;
use firefam_app_server_protocol::Thread;
use firefam_app_server_protocol::ThreadApproveGuardianDeniedActionParams;
use firefam_app_server_protocol::ThreadApproveGuardianDeniedActionResponse;
use firefam_app_server_protocol::ThreadArchiveParams;
use firefam_app_server_protocol::ThreadArchiveResponse;
use firefam_app_server_protocol::ThreadArchivedNotification;
use firefam_app_server_protocol::ThreadBackgroundTerminalsCleanParams;
use firefam_app_server_protocol::ThreadBackgroundTerminalsCleanResponse;
use firefam_app_server_protocol::ThreadClosedNotification;
use firefam_app_server_protocol::ThreadCompactStartParams;
use firefam_app_server_protocol::ThreadCompactStartResponse;
use firefam_app_server_protocol::ThreadDecrementElicitationParams;
use firefam_app_server_protocol::ThreadDecrementElicitationResponse;
use firefam_app_server_protocol::ThreadForkParams;
use firefam_app_server_protocol::ThreadForkResponse;
use firefam_app_server_protocol::ThreadGoal;
use firefam_app_server_protocol::ThreadGoalClearParams;
use firefam_app_server_protocol::ThreadGoalClearResponse;
use firefam_app_server_protocol::ThreadGoalClearedNotification;
use firefam_app_server_protocol::ThreadGoalGetParams;
use firefam_app_server_protocol::ThreadGoalGetResponse;
use firefam_app_server_protocol::ThreadGoalSetParams;
use firefam_app_server_protocol::ThreadGoalSetResponse;
use firefam_app_server_protocol::ThreadGoalStatus;
use firefam_app_server_protocol::ThreadGoalUpdatedNotification;
use firefam_app_server_protocol::ThreadHistoryBuilder;
use firefam_app_server_protocol::ThreadIncrementElicitationParams;
use firefam_app_server_protocol::ThreadIncrementElicitationResponse;
use firefam_app_server_protocol::ThreadInjectItemsParams;
use firefam_app_server_protocol::ThreadInjectItemsResponse;
use firefam_app_server_protocol::ThreadItem;
use firefam_app_server_protocol::ThreadListCwdFilter;
use firefam_app_server_protocol::ThreadListParams;
use firefam_app_server_protocol::ThreadListResponse;
use firefam_app_server_protocol::ThreadLoadedListParams;
use firefam_app_server_protocol::ThreadLoadedListResponse;
use firefam_app_server_protocol::ThreadMemoryModeSetParams;
use firefam_app_server_protocol::ThreadMemoryModeSetResponse;
use firefam_app_server_protocol::ThreadMetadataGitInfoUpdateParams;
use firefam_app_server_protocol::ThreadMetadataUpdateParams;
use firefam_app_server_protocol::ThreadMetadataUpdateResponse;
use firefam_app_server_protocol::ThreadNameUpdatedNotification;
use firefam_app_server_protocol::ThreadReadParams;
use firefam_app_server_protocol::ThreadReadResponse;
use firefam_app_server_protocol::ThreadRealtimeAppendAudioParams;
use firefam_app_server_protocol::ThreadRealtimeAppendAudioResponse;
use firefam_app_server_protocol::ThreadRealtimeAppendTextParams;
use firefam_app_server_protocol::ThreadRealtimeAppendTextResponse;
use firefam_app_server_protocol::ThreadRealtimeListVoicesResponse;
use firefam_app_server_protocol::ThreadRealtimeStartParams;
use firefam_app_server_protocol::ThreadRealtimeStartResponse;
use firefam_app_server_protocol::ThreadRealtimeStartTransport;
use firefam_app_server_protocol::ThreadRealtimeStopParams;
use firefam_app_server_protocol::ThreadRealtimeStopResponse;
use firefam_app_server_protocol::ThreadResumeParams;
use firefam_app_server_protocol::ThreadResumeResponse;
use firefam_app_server_protocol::ThreadRollbackParams;
use firefam_app_server_protocol::ThreadSetNameParams;
use firefam_app_server_protocol::ThreadSetNameResponse;
use firefam_app_server_protocol::ThreadShellCommandParams;
use firefam_app_server_protocol::ThreadShellCommandResponse;
use firefam_app_server_protocol::ThreadSortKey;
use firefam_app_server_protocol::ThreadSourceKind;
use firefam_app_server_protocol::ThreadStartParams;
use firefam_app_server_protocol::ThreadStartResponse;
use firefam_app_server_protocol::ThreadStartedNotification;
use firefam_app_server_protocol::ThreadStatus;
use firefam_app_server_protocol::ThreadTurnsItemsListParams;
use firefam_app_server_protocol::ThreadTurnsListParams;
use firefam_app_server_protocol::ThreadTurnsListResponse;
use firefam_app_server_protocol::ThreadUnarchiveParams;
use firefam_app_server_protocol::ThreadUnarchiveResponse;
use firefam_app_server_protocol::ThreadUnarchivedNotification;
use firefam_app_server_protocol::ThreadUnsubscribeParams;
use firefam_app_server_protocol::ThreadUnsubscribeResponse;
use firefam_app_server_protocol::ThreadUnsubscribeStatus;
use firefam_app_server_protocol::Turn;
use firefam_app_server_protocol::TurnEnvironmentParams;
use firefam_app_server_protocol::TurnError;
use firefam_app_server_protocol::TurnInterruptParams;
use firefam_app_server_protocol::TurnInterruptResponse;
use firefam_app_server_protocol::TurnItemsView;
use firefam_app_server_protocol::TurnStartParams;
use firefam_app_server_protocol::TurnStartResponse;
use firefam_app_server_protocol::TurnStatus;
use firefam_app_server_protocol::TurnSteerParams;
use firefam_app_server_protocol::TurnSteerResponse;
use firefam_app_server_protocol::UserInput as V2UserInput;
use firefam_app_server_protocol::WindowsSandboxReadiness;
use firefam_app_server_protocol::WindowsSandboxReadinessResponse;
use firefam_app_server_protocol::WindowsSandboxSetupCompletedNotification;
use firefam_app_server_protocol::WindowsSandboxSetupMode;
use firefam_app_server_protocol::WindowsSandboxSetupStartParams;
use firefam_app_server_protocol::WindowsSandboxSetupStartResponse;
use firefam_arg0::Arg0DispatchPaths;
use firefam_backend_client::AddCreditsNudgeCreditType as BackendAddCreditsNudgeCreditType;
use firefam_backend_client::Client as BackendClient;
use firefam_chatgpt::connectors;
use firefam_chatgpt::workspace_settings;
use firefam_config::CloudRequirementsLoadError;
use firefam_config::CloudRequirementsLoadErrorCode;
use firefam_config::ConfigLayerStack;
use firefam_config::loader::project_trust_key;
use firefam_config::types::McpServerTransportConfig;
use firefam_core::ExternalGoalPreviousStatus;
use firefam_core::ExternalGoalSet;
use firefam_core::FirefamThread;
use firefam_core::FirefamThreadSettingsOverrides;
use firefam_core::ForkSnapshot;
use firefam_core::NewThread;
#[cfg(test)]
use firefam_core::SessionMeta;
use firefam_core::StartThreadOptions;
use firefam_core::SteerInputError;
use firefam_core::ThreadConfigSnapshot;
use firefam_core::ThreadManager;
use firefam_core::config::Config;
use firefam_core::config::ConfigOverrides;
use firefam_core::config::NetworkProxyAuditMetadata;
use firefam_core::config::edit::ConfigEdit;
use firefam_core::config::edit::ConfigEditsBuilder;
use firefam_core::connectors::AccessibleConnectorsStatus;
use firefam_core::exec::ExecCapturePolicy;
use firefam_core::exec::ExecExpiration;
use firefam_core::exec::ExecParams;
use firefam_core::exec_env::create_env;
use firefam_core::path_utils;
#[cfg(test)]
use firefam_core::read_head_for_summary;
use firefam_core::sandboxing::SandboxPermissions;
use firefam_core::windows_sandbox::WindowsSandboxLevelExt;
use firefam_core::windows_sandbox::WindowsSandboxSetupMode as CoreWindowsSandboxSetupMode;
use firefam_core::windows_sandbox::WindowsSandboxSetupRequest;
use firefam_core::windows_sandbox::sandbox_setup_is_complete;
use firefam_core_plugins::FIREFAMAI_CURATED_MARKETPLACE_NAME;
use firefam_core_plugins::PluginInstallError as CorePluginInstallError;
use firefam_core_plugins::PluginInstallRequest;
use firefam_core_plugins::PluginLoadOutcome;
use firefam_core_plugins::PluginReadRequest;
use firefam_core_plugins::PluginUninstallError as CorePluginUninstallError;
use firefam_core_plugins::loader::load_plugin_apps;
use firefam_core_plugins::loader::load_plugin_mcp_servers;
use firefam_core_plugins::loader::plugin_telemetry_metadata_from_root;
use firefam_core_plugins::manifest::PluginManifestInterface;
use firefam_core_plugins::marketplace::MarketplaceError;
use firefam_core_plugins::marketplace::MarketplacePluginSource;
use firefam_core_plugins::marketplace_add::MarketplaceAddError;
use firefam_core_plugins::marketplace_add::MarketplaceAddRequest;
use firefam_core_plugins::marketplace_add::add_marketplace as add_marketplace_to_firefam_home;
use firefam_core_plugins::marketplace_remove::MarketplaceRemoveError;
use firefam_core_plugins::marketplace_remove::MarketplaceRemoveRequest as CoreMarketplaceRemoveRequest;
use firefam_core_plugins::marketplace_remove::remove_marketplace;
use firefam_core_plugins::remote::RemoteMarketplace;
use firefam_core_plugins::remote::RemoteMarketplaceSource;
use firefam_core_plugins::remote::RemotePluginCatalogError;
use firefam_core_plugins::remote::RemotePluginDetail as RemoteCatalogPluginDetail;
use firefam_core_plugins::remote::RemotePluginServiceConfig;
use firefam_core_plugins::remote::RemotePluginShareContext as RemoteCatalogPluginShareContext;
use firefam_core_plugins::remote::RemotePluginShareSummary as RemoteCatalogPluginShareSummary;
use firefam_core_plugins::remote::RemotePluginSummary as RemoteCatalogPluginSummary;
use firefam_exec_server::EnvironmentManager;
use firefam_exec_server::LOCAL_FS;
use firefam_features::FEATURES;
use firefam_features::Feature;
use firefam_features::Stage;
use firefam_feedback::FeedbackAttachmentPath;
use firefam_feedback::FeedbackUploadOptions;
use firefam_feedback::FirefamFeedback;
use firefam_git_utils::git_diff_to_remote;
use firefam_git_utils::resolve_root_git_project_for_trust;
use firefam_login::AuthManager;
use firefam_login::CLIENT_ID;
use firefam_login::FirefamAuth;
use firefam_login::ServerOptions as LoginServerOptions;
use firefam_login::ShutdownHandle;
use firefam_login::auth::login_with_chatgpt_auth_tokens;
use firefam_login::complete_device_code_login;
use firefam_login::login_with_api_key;
use firefam_login::request_device_code;
use firefam_login::run_login_server;
use firefam_mcp::McpRuntimeEnvironment;
use firefam_mcp::McpServerStatusSnapshot;
use firefam_mcp::McpSnapshotDetail;
use firefam_mcp::collect_mcp_server_status_snapshot_with_detail;
use firefam_mcp::discover_supported_scopes;
use firefam_mcp::effective_mcp_servers;
use firefam_mcp::read_mcp_resource as read_mcp_resource_without_thread;
use firefam_mcp::resolve_oauth_scopes;
use firefam_memories_write::clear_memory_roots_contents;
use firefam_model_provider::ProviderAccountError;
use firefam_model_provider::create_model_provider;
use firefam_models_manager::collaboration_mode_presets::builtin_collaboration_mode_presets;
use firefam_protocol::ThreadId;
use firefam_protocol::config_types::CollaborationMode;
use firefam_protocol::config_types::ForcedLoginMethod;
use firefam_protocol::config_types::Personality;
use firefam_protocol::config_types::TrustLevel;
use firefam_protocol::config_types::WindowsSandboxLevel;
use firefam_protocol::dynamic_tools::DynamicToolSpec as CoreDynamicToolSpec;
use firefam_protocol::error::FirefamErr;
use firefam_protocol::error::Result as FirefamResult;
#[cfg(test)]
use firefam_protocol::items::TurnItem;
use firefam_protocol::models::BUILT_IN_PERMISSION_PROFILE_DANGER_FULL_ACCESS;
use firefam_protocol::models::BUILT_IN_PERMISSION_PROFILE_READ_ONLY;
use firefam_protocol::models::BUILT_IN_PERMISSION_PROFILE_WORKSPACE;
use firefam_protocol::models::ResponseItem;
#[cfg(test)]
use firefam_protocol::permissions::FileSystemSandboxPolicy;
use firefam_protocol::protocol::AgentStatus;
use firefam_protocol::protocol::ConversationAudioParams;
use firefam_protocol::protocol::ConversationStartParams;
use firefam_protocol::protocol::ConversationStartTransport;
use firefam_protocol::protocol::ConversationTextParams;
use firefam_protocol::protocol::EventMsg;
#[cfg(test)]
use firefam_protocol::protocol::GitInfo as CoreGitInfo;
use firefam_protocol::protocol::InitialHistory;
use firefam_protocol::protocol::McpAuthStatus as CoreMcpAuthStatus;
use firefam_protocol::protocol::Op;
use firefam_protocol::protocol::RateLimitSnapshot as CoreRateLimitSnapshot;
use firefam_protocol::protocol::RealtimeVoicesList;
use firefam_protocol::protocol::ResumedHistory;
use firefam_protocol::protocol::ReviewDelivery as CoreReviewDelivery;
use firefam_protocol::protocol::ReviewRequest;
use firefam_protocol::protocol::ReviewTarget as CoreReviewTarget;
use firefam_protocol::protocol::RolloutItem;
use firefam_protocol::protocol::SessionConfiguredEvent;
#[cfg(test)]
use firefam_protocol::protocol::SessionMetaLine;
use firefam_protocol::protocol::TurnEnvironmentSelection;
use firefam_protocol::protocol::USER_MESSAGE_BEGIN;
use firefam_protocol::protocol::W3cTraceContext;
use firefam_protocol::user_input::MAX_USER_INPUT_TEXT_CHARS;
use firefam_protocol::user_input::UserInput as CoreInputItem;
use firefam_rmcp_client::perform_oauth_login_return_url;
use firefam_rollout::EventPersistenceMode;
use firefam_rollout::is_persisted_rollout_item;
use firefam_rollout::state_db::StateDbHandle;
use firefam_rollout::state_db::reconcile_rollout;
use firefam_state::ThreadMetadata;
use firefam_state::log_db::LogDbLayer;
use firefam_thread_store::ArchiveThreadParams as StoreArchiveThreadParams;
use firefam_thread_store::GitInfoPatch as StoreGitInfoPatch;
use firefam_thread_store::ListThreadsParams as StoreListThreadsParams;
use firefam_thread_store::LocalThreadStore;
use firefam_thread_store::ReadThreadByRolloutPathParams as StoreReadThreadByRolloutPathParams;
use firefam_thread_store::ReadThreadParams as StoreReadThreadParams;
use firefam_thread_store::SortDirection as StoreSortDirection;
use firefam_thread_store::StoredThread;
use firefam_thread_store::ThreadMetadataPatch as StoreThreadMetadataPatch;
use firefam_thread_store::ThreadSortKey as StoreThreadSortKey;
use firefam_thread_store::ThreadStore;
use firefam_thread_store::ThreadStoreError;
use firefam_utils_absolute_path::AbsolutePathBuf;
use firefam_utils_pty::DEFAULT_OUTPUT_BYTES_CAP;
use std::collections::HashMap;
use std::collections::HashSet;
use std::io::Error as IoError;
use std::path::Path;
use std::path::PathBuf;
use std::result::Result;
use std::sync::Arc;
use std::time::Duration;
use std::time::Instant;
use tokio::sync::Mutex;
use tokio::sync::Semaphore;
use tokio::sync::SemaphorePermit;
use tokio::sync::broadcast;
use tokio::sync::oneshot;
use tokio::sync::watch;
use tokio_util::sync::CancellationToken;
use tokio_util::task::TaskTracker;
use toml::Value as TomlValue;
use tracing::Instrument;
use tracing::error;
use tracing::info;
use tracing::warn;
use uuid::Uuid;

#[cfg(test)]
use firefam_app_server_protocol::ServerRequest;

mod account_processor;
mod apps_processor;
mod catalog_processor;
mod command_exec_processor;
mod config_processor;
mod environment_processor;
mod external_agent_config_processor;
mod feedback_doctor_report;
mod feedback_processor;
mod fs_processor;
mod git_processor;
mod initialize_processor;
mod marketplace_processor;
mod mcp_processor;
mod plugins;
mod process_exec_processor;
mod remote_control_processor;
mod search;
mod thread_processor;
mod token_usage_replay;
mod turn_processor;
mod windows_sandbox_processor;

pub(crate) use account_processor::AccountRequestProcessor;
pub(crate) use apps_processor::AppsRequestProcessor;
pub(crate) use catalog_processor::CatalogRequestProcessor;
pub(crate) use command_exec_processor::CommandExecRequestProcessor;
pub(crate) use config_processor::ConfigRequestProcessor;
pub(crate) use environment_processor::EnvironmentRequestProcessor;
pub(crate) use external_agent_config_processor::ExternalAgentConfigRequestProcessor;
pub(crate) use feedback_processor::FeedbackRequestProcessor;
pub(crate) use fs_processor::FsRequestProcessor;
pub(crate) use git_processor::GitRequestProcessor;
pub(crate) use initialize_processor::InitializeRequestProcessor;
pub(crate) use marketplace_processor::MarketplaceRequestProcessor;
pub(crate) use mcp_processor::McpRequestProcessor;
pub(crate) use plugins::PluginRequestProcessor;
pub(crate) use process_exec_processor::ProcessExecRequestProcessor;
pub(crate) use remote_control_processor::RemoteControlRequestProcessor;
pub(crate) use search::SearchRequestProcessor;
pub(crate) use thread_goal_processor::ThreadGoalRequestProcessor;
pub(crate) use thread_processor::ThreadRequestProcessor;
pub(crate) use turn_processor::TurnRequestProcessor;
pub(crate) use windows_sandbox_processor::WindowsSandboxRequestProcessor;

use crate::error_code::internal_error;
use crate::error_code::invalid_request;
use crate::filters::compute_source_filters;
use crate::filters::source_kind_matches;
use crate::thread_state::ConnectionCapabilities;
use crate::thread_state::ThreadListenerCommand;
use crate::thread_state::ThreadState;
use crate::thread_state::ThreadStateManager;
use token_usage_replay::latest_token_usage_turn_id_from_rollout_items;
use token_usage_replay::send_thread_token_usage_update_to_connection;

mod config_errors;
mod request_errors;
mod thread_goal_processor;
mod thread_lifecycle;
mod thread_resume_redaction;
mod thread_summary;

use self::config_errors::*;
use self::request_errors::*;
use self::thread_goal_processor::api_thread_goal_from_state;
use self::thread_lifecycle::*;
use self::thread_resume_redaction::*;
use self::thread_summary::*;

pub(crate) use self::thread_lifecycle::populate_thread_turns_from_history;
pub(crate) use self::thread_processor::thread_from_stored_thread;
#[cfg(test)]
pub(crate) use self::thread_summary::read_summary_from_rollout;
#[cfg(test)]
pub(crate) use self::thread_summary::summary_to_thread;

pub(crate) fn build_api_turns_from_rollout_items(items: &[RolloutItem]) -> Vec<Turn> {
    let mut builder = ThreadHistoryBuilder::new();
    for item in items {
        if is_persisted_rollout_item(item, EventPersistenceMode::Limited) {
            builder.handle_rollout_item(item);
        }
    }
    builder.finish()
}
